#!/bin/sh -e

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
RED='\033[1;31m'
NC='\033[0m'

SYSTEM_TYPE="aarch64-darwin"
FLAKE_SYSTEM="darwinConfigurations.${SYSTEM_TYPE}.system"

export NIXPKGS_ALLOW_UNFREE=1

echo "${YELLOW}Checking for changes in the repository...${NC}"
if git diff --quiet && git diff --cached --quiet; then
	echo "${GREEN}No changes to commit.${NC}"
else
	echo "${YELLOW}Uncommitted changes found.${NC}"
	printf "Enter commit message:\n"
	read -r COMMIT_MESSAGE

	if [ -z "$COMMIT_MESSAGE" ]; then
		echo "${RED}Commit message cannot be empty.${NC}"
		exit 1
	fi

	git add .
	git commit -m "$COMMIT_MESSAGE"
	echo "${GREEN}Committed${NC}"
fi

echo "${YELLOW}Starting build...${NC}"
nix --extra-experimental-features 'nix-command flakes' build .#$FLAKE_SYSTEM $@

echo "${YELLOW}Switching to new generation...${NC}"
./result/sw/bin/darwin-rebuild switch --flake .#${SYSTEM_TYPE} $@

echo "${YELLOW}Cleaning up...${NC}"
unlink ./result

echo "${GREEN}Switch to new generation complete!${NC}"
